import { Inter } from "next/font/google";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Shopify + Next.js 13!",
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen container mx-auto px-4 sm:px-6 lg:px-8`}
      >
        <Navbar />
        <section className="flex flex-1">{children}</section>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
